#!/bin/bash
ID=$1
bin_path=$2

cat $ID | awk '{
decision=0;
if($2~/^[1-2]?[0-9]$/ || $2=="X"){
	cmd ="head -n 2  '$bin_path'"$2".norm.bin | tail -n 1"
	cmd | getline SNP_start
	close(cmd)
	split(SNP_start,start_f,sep="\t");
        cmd ="tail -n 1 '$bin_path'"$2".norm.bin"
        cmd | getline SNP_end
        close(cmd)
        split(SNP_end,end_f,sep="\t");
	if($3>start_f[1]&&$3<end_f[2])
		decision=decision+1;
}
if($4~/^[1-2]?[0-9]$/ || $4=="X"){
        cmd ="head -n 2  '$bin_path'"$4".norm.bin | tail -n 1"
        cmd | getline SNP_start
        close(cmd)
        split(SNP_start,start_f,sep="\t");
        cmd ="tail -n 1 '$bin_path'"$4".norm.bin"
        cmd | getline SNP_end
        close(cmd)
        split(SNP_end,end_f,sep="\t");
        if($5>start_f[1]&&$5<end_f[2])
		decision=decision+1;
}
if(decision==2)
	print $0 > "'$ID'.truncated"



}'
mv $ID.truncated $ID
